# Generated by Django 4.0.4 on 2022-04-26 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_comment_likes_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to='network.comment'),
        ),
        migrations.AddField(
            model_name='user',
            name='liked_post',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_user', to='network.post'),
        ),
    ]
